### ISSUE TITLE
Files Linked but Not Included

### ISSUE THREAD

**Issue by DenVog** [cocoabits/MASShortcutDemo#1]
FYI - The MASShortcut Demo does not seem to have the class files included with it. The MASShortcut folder is empty in finder, and attempting to build will give an error File not found. Maybe you created links to the files but did not check Copy item's into destination group's folder or Add to targets?

Simple enough to fix on this end by coping the class files from the parent project, but I thought you would want to be aware.

Thank you for sharing this awesome project.

**Comment by shpakovski** [comment]
The demo project repository is enabling another repository as a git submodule. To download class files automatically, you would type something like `git submodules --init --update` in Terminal. You are welcome!

**Comment by DenVog** [comment]
Ah. I did not pull the project via terminal. I downloaded it via the ZIP download button. Thanks.
